# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13b41ff7e634a3a3fb2c2b90215b2819580f575ce4e727241ad9a1c579236a9273f4b83d3e915671dc531e4058a2f5372565a80e37362b7c409cf1f0046891c6

test:
  secret_key_base: 3b08178d273100059c83dfb26a03aea297698e273093db91be6d41c39c1782719c2f14a15bd29237543d3c887626beb393dee4d2eac3abd3aef78f91c3cae80d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
